version: "3.9"
services:
  csvserver:
    volumes:
      - ./inputdata:/csvserver/inputdata
    ports:
      - "9393:9300"
    image: infracloudio/csvserver:latest
    environment:
      - CSVSERVER_BORDER=Orange

  prometheus:
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    image: "prom/prometheus:v2.22.0"
    command: --config.file=/etc/prometheus/prometheus.yml --web.enable-lifecycle
